# Generated by Django 2.2.7 on 2019-11-22 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bank_phone_number',
            field=models.CharField(max_length=12),
        ),
    ]
